package utils

type ERROR_CODE string

const (
	UNKNOWN_ERROR ERROR_CODE = "UNKNOWN_ERROR"
	VALIDATION_ERROR ERROR_CODE = "VALIDATION_ERROR"
	MISSING_PARAMS ERROR_CODE = "MISSING_PARAMS"
	NOT_FOUND_ERROR ERROR_CODE = "NOT_FOUND_ERROR"
	INTERNAL_ERROR ERROR_CODE = "INTERNAL_ERROR"
	NOT_AUTHORIZED ERROR_CODE = "NOT_AUTHORIZED"
	NOT_AUTHENTICATED ERROR_CODE = "NOT_AUTHENTICATED"
	CREATING_ERROR ERROR_CODE = "CREATING_ERROR"
	LISTING_ERROR ERROR_CODE = "LISTING_ERROR"
	DELETING_ERROR ERROR_CODE = "DELETING_ERROR"
	UPDATE_ERROR ERROR_CODE = "UPDATE_ERROR"
	EMAIL_ALREADY_EXISTS ERROR_CODE = "EMAIL_ALREADY_EXISTS"
)